# Generated by Django 5.1.4 on 2024-12-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salary_by_year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_salary', models.FloatField()),
                ('year', models.IntegerField()),
            ],
            options={
                'db_table': 'salaries_by_year',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('key_skills', models.TextField()),
                ('salary_from', models.FloatField(blank=True, null=True)),
                ('salary_to', models.FloatField(blank=True, null=True)),
                ('salary_currency', models.CharField(max_length=5)),
                ('area_name', models.CharField(max_length=50)),
                ('published_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('currency_code', models.CharField(max_length=5)),
                ('currency', models.FloatField()),
            ],
            options={
                'db_table': 'currencies',
                'unique_together': {('date', 'currency_code')},
            },
        ),
    ]
