# Generated by Django 5.1.4 on 2024-12-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20241227_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancies_by_year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_count', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
            options={
                'db_table': 'vacancies_by_year',
            },
        ),
    ]
