# Generated by Django 5.1.4 on 2024-12-28 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_salary_by_city_vacancies_by_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancies_by_city',
            old_name='vanacy_share',
            new_name='vacancy_share',
        ),
    ]
