# Generated by Django 5.1.4 on 2024-12-28 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_rename_vanacy_share_vacancies_by_city_vacancy_share'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salary_by_city',
            options={'verbose_name_plural': 'salaries_by_city'},
        ),
        migrations.AlterModelOptions(
            name='vacancies_by_city',
            options={'verbose_name_plural': 'vacancies_by_city'},
        ),
    ]
