# Generated by Django 5.1.4 on 2025-01-05 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_top_skills'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterModelOptions(
            name='salary_by_year',
            options={'verbose_name_plural': 'Salaries_by_years'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name_plural': 'Vacancies'},
        ),
    ]
